#!/bin/bash
#create mles script
HOST_PARM="-h"
HOST_NAME=""
INFO=""
PORT=8443
ShowPollHostExample()
{
   echo -e "PollHost example:\n\033[31;49;5;1m bash oat_pollhosts -h HOSTNAME_OF_OAT-APPRAISER '{"hosts":["HOSTNAME_OF_OAT-CLIENT"]}' \033[0m"
}

if [ $# -lt 3 ];then
  echo "parm num error!"
  ShowPollHostExample
  exit 0
fi

if [ $1 != $HOST_PARM ];then
  echo "-h parm error!"
  ShowPollHostExample
  exit 1
else
  HOST_NAME="$2"
fi

INFO="$3"

pollHosts()
{
  curl --cacert certfile.cer -H "Content-Type: application/json" \
        -X POST -d "$INFO" "https://$HOST_NAME:$PORT/AttestationService/resources/PollHosts"
}
pollHosts
echo -e "\n"
